import React from "react";
import {
  Check,
  X,
  ChevronLeft as ArrowLeft,
  ChevronRight as ArrowRight,
  GraduationCap,
  ShoppingBag,
  Tag,
  MessageCircle,
  Users,
  LayoutGrid,
  MousePointer,
  Search,
  Filter,
  ArrowDown,
  Upload,
  PlusCircle,
  UserCircle,
  Settings,
  LogIn,
  CheckCircle,
  AlertCircle,
  Share2,
  Zap,
  Menu,
  LogOut,
  Heart,
  Home,
  Box,
  MessageSquare,
  ShoppingCart,
  User,
  Package,
  Send,
  Image,
  Camera,
  Trash,
  Edit,
  Copy,
  Share,
  Phone,
  Clipboard,
  CreditCard,
  HelpCircle,
  AlertTriangle,
  Save,
  FileText,
  Bell,
  Mail,
  Star,
  Info,
  Calendar,
  ChevronDown,
  MoreHorizontal,
  ExternalLink,
  Plus,
  Minus,
  DollarSign,
} from "lucide-react";

export const Icons = {
  check: Check,
  x: X,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  graduationCap: GraduationCap,
  shoppingBag: ShoppingBag,
  tag: Tag,
  messageCircle: MessageCircle,
  users: Users,
  layoutGrid: LayoutGrid,
  mousePointer: MousePointer,
  search: Search,
  filter: Filter,
  arrowDown: ArrowDown,
  upload: Upload,
  plusCircle: PlusCircle,
  userCircle: UserCircle,
  settings: Settings,
  logIn: LogIn,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  share2: Share2,
  zap: Zap,
  menu: Menu,
  logOut: LogOut,
  heart: Heart,
  home: Home,
  box: Box,
  messageSquare: MessageSquare,
  shoppingCart: ShoppingCart,
  user: User,
  package: Package,
  send: Send,
  image: Image,
  camera: Camera,
  trash: Trash,
  edit: Edit,
  copy: Copy,
  share: Share,
  phone: Phone,
  clipboard: Clipboard,
  creditCard: CreditCard,
  helpCircle: HelpCircle,
  alertTriangle: AlertTriangle,
  save: Save,
  fileText: FileText,
  bell: Bell,
  mail: Mail,
  star: Star,
  info: Info,
  calendar: Calendar,
  chevronDown: ChevronDown,
  moreHorizontal: MoreHorizontal,
  externalLink: ExternalLink,
  plus: Plus,
  minus: Minus,
  dollarSign: DollarSign,
};